file_format: "1"
id: soflex
name: SofleX
type: shield
url: https://github.com/josefadamcik/SofleKeyboard
# requires: [seeeduino_xiao_ble]
requires: [seeed_xiao]
features:
  - keys
siblings:
  - soflex_left
  - soflex_right
